language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install mkdocs 
  - pip install awscli
# command to run tests
script: 
  - mkdocs build
  - aws --region us-west-2 s3 sync site s3://hazybits.com/docs