language: python
python:
- '2.7'
install:
- pip install mkdocs
- pip install mkdocs-material
- pip install awscli
script:
- mkdocs build
- aws --region us-west-2 s3 sync site s3://hazybits.com/docs
notifications:
  slack:
    secure: P4BSaMXkZHumTC4TxFix/NmE4+H+sBMjdUwp97dvFwCu+ne+5XMRtL8C4PnyBNVo2jmhs1DmszR7d3r4cyyVBBBPqmcdz2EicrIu516lYyKhFgXoewZ+xjr6SpJ7nsUT2zpr0RjX/iwhf441yA3Ye8HulSExQqwsh6Iwf/nLYHlpvjcr4cBvQ/vOYaCChlW6XC5ZE5COI+SR8QqJVy7+kFrT4QbY3LCZ39WeATn0ALNjHg1o4COo6+Xy+82sOL4UIMosZcFlNZNIHajPaxeNqIhHhK1eqW+/vRJ50Y+OzPQReGVZzk1di6qFN4pPph3wA80CF+LwEndr3IoOucvCacgLXjO4TW7/PTOhErj+efwYrYKnu0ZrH83xEkYOU2VolmJ7YgFRqiapWqfYm9xTVKR0q8XzAPItLv8Pl3PLnMpBnf641Ro5WQ3hBnwJaeWL/zK6od3vLV7lnrjIJDjdE3UcxZun9ySByvTlHap56yx1z0A61mgEYsao9AlvHa2s8Xj220bfuLEk6hkbJvFq5qGiwgtqoz6aLivftZbpy1EyrcteyHfPTsL8vfGt+1+f1mYZ9K3hRQzPUmWfvtu+BklZL9h2/Hhj/y1fbtyZHIUN7r/ldHzXAetfHgEC8oi98VmTue0jz2MkcbNCPDYNW82b5tbVoqkBw3drb8TG+NA=
