# Project information
site_name: HazyBits Documentation
site_description: Main Documentation source for HazyBits platform.
site_author: HazyBits
site_url: 'https://hazybits.com/docs'
site_favicon: 'favicon.ico'

# Repository
repo_name: 'hazy-bits/hazybits-docs'
repo_url: 'https://github.com/hazy-bits/hazybits-docs'

# Copyright
copyright: 'HazyBits &nbsp;&bull;&nbsp; 2017'

theme: material

extra:
#  font:
#    text: 'Ubuntu'
#    code: 'Ubuntu Mono'

  social:
    - type: 'github'
      link: 'https://github.com/hazy-bits'
    - type: 'twitter'
      link: 'https://twitter.com/hazy_bits'
    - type: 'facebook'
      link: 'https://www.facebook.com/hazybits.cloud/'

  disqus: 'hazybits-docs'

# Google Analytics
google_analytics:
  - 'UA-107512395-2'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)

pages:
- Home: 'index.md'
- Development:
    - 'Node JS modules': 'development/node-js-modules.md'
    - 'AWS Services': 'development/aws-services.md'
    - 'AWS Lamba functions': 'development/aws-lambda-functions.md'
    - 'AWS Workflows': 'development/aws-workflows.md'
- Deployment:
    - 'Process': 'deployment/process.md'
- Usage:
    - 'Web API': 'usage/web-api.md'
